name: synology_api
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/adbonnin/synology_api

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
